### ISSUE TITLE
Could not open image; image format not recognized

### ISSUE THREAD

**Issue by QiWang-SJTU** [jerabaul29/Cylinder2DFlowControlDRL#19] opened 2020-11-28 05:30 UTC
Hi, 

I installed the Singularity and put the segments from the container folder together. 
Then I tried to run the following line, but I got a Fatal Error: 

```
singularity shell ~/Cylinder2DFlowControlDRL-master/container/fenics-and-more.img -c "export DISPLAY=:0.0 && export PATH="~/gmsh-3.0.6-Linux64/bin:$PATH" && /bin/bash"

FATAL:   could not open image /home/zww/Cylinder2DFlowControlDRL-master/container/fenics-and-more.img: image format not recognized
```

would you please give me some ideas about this?

Thanks very much.

**Comment by jerabaul29** [comment] 2020-11-28 07:48
Hi,

Mmh, strange, never heard of something like this before.

If you take the sha256sum of your img, what do you get? Does it match the sha256sum given in the readme?

**Comment by QiWang-SJTU** [comment] 2020-11-28 08:51
Thanks for your reply,
Actually the code is not the same, as follows:

141a0faf677f1d24d2e7643a9c763c355a18e34a7ccfc33d7ce4ef65524c004a  fenics-and-more.img

What it indicates exactly?

**Comment by jerabaul29** [comment] 2020-11-28 09:04
It means that the container you re-assembled is not identical to the initial container. That explains why it cannot be loaded.

Are you sure that you used the exact command

```
cat fenics-and-more.img_part.?? > fenics-and-more.img
```

To assemble your container, and that you had all segments? Can you try again?

**Comment by jerabaul29** [comment] 2020-11-28 09:05
Ie do you well have all parts aa->af for performing the reconstruction?

**Comment by QiWang-SJTU** [comment] 2020-11-28 09:21
Yes, I'm Sure.

I have all parts aa->af and the command used is totally the same.  I tried many times but got the same results.

It is strange.

**Comment by jerabaul29** [comment] 2020-11-28 09:26
Ok. I will look at it later today and I let you know.

**Comment by QiWang-SJTU** [comment] 2020-11-28 09:32
Ok. Thanks for your kind help.

**Comment by jerabaul29** [comment] 2020-11-28 10:10
I am still not back to my computer but was thinking; would you want to try with this instead?

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel

It uses docker instead of singularity, and has enhanced functionality (using some DRL parallelization), otherwise mostly the same.

**Comment by QiWang-SJTU** [comment] 2020-11-28 13:39
Ok, I will try it later.

Thanks for your patience.

**Comment by jerabaul29** [comment] 2020-11-28 20:17
Ok, so everything works, the problem is with github serving these large git-lfs files.

What I did was:

- Go to the container folder: ```https://github.com/jerabaul29/Cylinder2DFlowControlDRL/tree/master/container```

- Download by hand using the github web GUI all fragments, i.e. for each fragment 1) click on the filename 2) click on the "download" button

Once I did this and assembled the container, the container was correct and I got the right checksum. After that, the readme works as needed.

The problems seems to be that, while git-lfs should allow to check in / out large files, there is a problem due to either github or git locally when checking out these large fragment files.

I will update the readme with this information, thank you for letting me know. Can you confirm if this allows you to 1) successfully download all fragments 2) successfully assemble the container and get the right checksum 3) use the container.

**Comment by jerabaul29** [comment] 2020-11-28 20:24
Updated the readme. Will be happy to hear if this fixes things for you too. It should :) .

**Comment by jerabaul29** [comment] 2020-11-28 20:25
(I still recommend that you rather use the code on the parallel repo, it is better).

**Comment by QiWang-SJTU** [comment] 2020-11-29 04:17
Yes, 

1) I can download all fragments correctly.
2) The checksum also matched well.
3) But I still got an error when I run the code, for example , python single_runner.py in Singularity.   As follows:

Singularity> python single_runner.py 
[zww-System-Product-Name:15534] mca: base: component_find: unable to open /home/zww/packages/openmpi-1.10.7/opt-gfortran/lib/openmpi/mca_coll_libnbc: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/zww/packages/openmpi-1.10.7/opt-gfortran/lib/openmpi/mca_coll_libnbc.so) (ignored)
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  mca_coll_base_comm_select(MPI_COMM_WORLD) failed
  --> Returned "Not found" (-13) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[zww-System-Product-Name:15534] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
Singularity> 

The error is about the Open-MPI. I am not an expert on this :(

I will try to use the code on the parallel repo, but I am not sure whether the Open-MPI error will occur or not. Maybe I need to reinstall the system.

Anyway, thanks for your kind help. 

Best regards.

**Comment by QiWang-SJTU** [comment] 2020-11-29 07:11
Update, It works!

I use the code on the parallel repo with docker. 

Thanks for your sharing and kind help :)

**Comment by jerabaul29** [comment] 2020-11-29 08:18
Ok great that it works. Are you able to use both the singularity and the docker code? I tested both yesterday on my computer it worked. Possible you need to update your singularity and or docker.

But it seems you got things to work, closing. Open new issues if you have any problems :) .

My pleasure, great that it works now :)

**Closed as completed by jerabaul29** 2020-11-29 08:18 UTC
