### ISSUE TITLE
could not connect to display ":0.0"

### ISSUE THREAD

**Issue by turtle-mei** [jerabaul29/Cylinder2DFlowControlDRL#17] opened 2020-06-23 11:23 UTC
`Conversion done
      mesh_file = mesh/turek_2d.h5
-0.2 0.21
      total_number_of_probes = 151
No protocol specified
No protocol specified
Traceback (most recent call last):
  File "make_mesh.py", line 2, in <module>
    env.resume_env(plot=500, remesh=True)
  File "/home/yufeimei/Downloads/singularity-2.5.1/my img/ellipse/ellipse_y/baseline_flow/env.py", line 181, in resume_env
    simu_name = simu_name)
  File "/home/yufeimei/Downloads/singularity-2.5.1/my img/ellipse/ellipse_y/baseline_flow/../Env2DCylinder.py", line 132, in __init__
    self.start_class(complete_reset=True)
  File "/home/yufeimei/Downloads/singularity-2.5.1/my img/ellipse/ellipse_y/baseline_flow/../Env2DCylinder.py", line 286, in start_class
    self.visual_inspection()
  File "/home/yufeimei/Downloads/singularity-2.5.1/my img/ellipse/ellipse_y/baseline_flow/../Env2DCylinder.py", line 461, in visual_inspection
    plt.subplots(total_number_subplots, 1)
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 1177, in subplots
    fig = figure(**fig_kw)
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 84, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 92, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":0.0"
Aborted (core dumped)`

I can run the code correctly in debian,but there are some qusetions when i use a new ubantu.could not display ":0.0", It can not show the figure.can you give me some suggestions?

**Comment by jerabaul29** [comment] 2020-06-23 11:38
Ok, so:

- are you well trying to run the code through singularity (it looks like it, right?)
- it looks like the container you run is trying to display the output by connecting to a display ```:0.0```. This looks like the root of the problen.

I suppose this is enabled by default on Ubuntu but not on Debian, or differently on different Ubuntu versions, or something like that. 

This is then related to this issue:

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/issues/7

According to the comments there, it was probably solved by following the advise:

"ry to export on a different display: see https://unix.stackexchange.com/questions/85782/error-no-protocol-specified-when-running-from-remote-machine-via-ssh/295863#295863 the recommendation export DISPLAY=:10".

Can you 1) have a look at this solution, 2) let me know if it fixes your problem?

If this does not fix it, can you provide the exact details of the system you use for running?

If it still does not work, could you consider using the code there instead, which is about 1 year newer and may run without problems (it is basically an expansion / improvement of this code): https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel

**Comment by turtle-mei** [comment] 2020-06-23 11:49
yes,I try to change the export DISPLAY=:10,but failed.
My system:processor:AMD Ryzen 7 3700x 8-core processor 16
graphics:quadro P620/PCle/SSE2.

**Comment by turtle-mei** [comment] 2020-06-23 11:50
ubantu 18.04.4

**Comment by jerabaul29** [comment] 2020-06-23 11:56
Mmh, ok. This is annoying, as this is the whole point of using containers, i.e., allow reproducibility. But I guess that as soon as there is some interaction with the host OS for displaying, then things start to potentially break... :(

Can you try the code from the other repo? https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel

The container is available either directly on the repo as fragments, or it should still be available at the 'old' location (will disappear in a few days there):  https://folk.uio.no/jeanra/Informatics/cylinder2dflowcontrol_Parallel_v1.tar

Another option that should solve the problem once and for all is to edit the code to remove the display and plotting commands, that are anyways not essential. Have you been able to run before on other systems?

**Comment by turtle-mei** [comment] 2020-06-23 12:02
yes,I use debian to run it succesfully before,and did some works.at last ,I change a high perform computer,and set up the ubantu.  maybe I think i will  try to use the new code !

**Comment by jerabaul29** [comment] 2020-06-23 12:12
Ok. Are you running through ssh, or directly on the machine? If you are running through ssh, you may need to forward the display or something like that: https://unix.stackexchange.com/questions/12755/how-to-forward-x-over-ssh-to-run-graphics-applications-remotely .

But I think that the best would indeed be to use the more recent code :) Let me know if you have issues with it on the corresponding repository. Also, if you have a good CPU with several cores, the more recent code will let you run several CFD simulations in parallel, which will allow to do the training much faster (more or less perfect speedup with the number of simulations, see the discussion here: https://aip.scitation.org/doi/full/10.1063/1.5116415 .

**Comment by turtle-mei** [comment] 2020-06-23 12:12
aaa,so happy ! It run succesfully.I commented the code that about plotting.and delete the export DISPLAY=:0.0.Then evering is good.Thank you for your suggestions.

**Comment by jerabaul29** [comment] 2020-06-23 12:17
Ok, great, good it helped and works now :) Of course the plotting is nice to start with, but it is not really needed anyways for heavy trainings, so should be fine without it (as long as only the plotting is commented out and there are no sides effects to the commenting you added) :) . But still, I would recommend you to have a look at the newer code, it is quite nicer and on your CPU with 8 cores, you should get a perfect speedup by a factor 8x by running 8 simulations, like: 

```bash script_launch_parallel.sh training_1 3000 8```

or something like that, if things are unclear just let me know on this repo :) .

**Comment by jerabaul29** [comment] 2020-06-23 12:18
But this is solved now, so closing, if you have any more problems feel free to re open :) .

**Closed as completed by jerabaul29** 2020-06-23 12:18 UTC
