### ISSUE TITLE
Change the model and run singlerunner from Ann_ controlled_ flow_ Singlerun folder, did not get the same result

### ISSUE THREAD

**Issue by gaogao188** [jerabaul29/Cylinder2DFlowControlDRL#20] opened 2020-12-20 08:11 UTC
Hi,
I used Gmsh to draw a cylinder model like you. Running baseline got the same result as you, but after adding control, I didn't get the same result as you.

thank you very mush.

**Comment by gaogao188** [comment] 2020-12-22 04:29
would you please give me some ideas about this?

Thank you for your reply

**Comment by jerabaul29** [comment] 2020-12-22 21:17
Hi,

It is difficult to know exactly what you are doing from your post. If your mesh is too coarse, or refined at the wrong place, you may get different results. If your domain has a different size, you may have more or less wall blocking effect and that may change slightly what control would be necessary. Maybe there is another subtle change somewhere between your and our configuration.

What I know for sure is:

- if you run the code from the present repo following the readme file, with the parameters in the repo and the container, it will produce the same figures

- people have reproduced our results with both different solvers and DRL frameworks, so the results in general are robust and reproducible; see for example https://www.mdpi.com/1996-1073/13/22/5920/htm and https://arxiv.org/pdf/2006.10683.pdf

Apart from this there is not really more I can say from the information you provide. You may try to perform a new learning in your configuration and see if the ANN can learn some control strategy. If yes, it will be interesting to investigate what the initial difference between your and our configuration was. Note that it is possible that the ANN provided here is little robust and that the control strategy is very sensitive to small changes in the simulation, since the ANN was trained specifically on only this simulation (i.e. no "generalization" to other, similar but slightly different configurations).

Maybe the ANN provided in this other (extension) work may be much more robust to changes in the configuration, as this was trained with the goal to be efficient across Reynolds numbers:

https://github.com/thw1021/Cylinder2DFlowControlGeneral

.

**Comment by jerabaul29** [comment] 2020-12-27 09:52
Without more details I think this may be user case dependent, closing for now.

**Closed as completed by jerabaul29** 2020-12-27 09:52 UTC
